CREATE TABLE DEPARTMENTS (
	DEPARTMENT_ID NUMBER(4) ,
	DEPARTMENT_NAME VARCHAR2(30),
	MANAGER_ID NUMBER(6),
	LOCATION_ID NUMBER(4),
	PRIMARY KEY(DEPARTMENT_ID)
);


CREATE TABLE EMPLOYEES (
EMPLOYEE_ID NUMBER(6),
FIRST_NAME VARCHAR2(20),
LAST_NAME VARCHAR2(25),
EMAIL VARCHAR2(25),
PHONE_NUMBER VARCHAR2(20),
HIRE_DATE DATE,
JOB_ID VARCHAR2(10),
SALARY NUMBER(8,2),
COMMISSION_PCT NUMBER(2,2),
MANAGER_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4),
PRIMARY KEY (EMPLOYEE_ID)
);

ALTER TABLE EMPLOYEES ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID);