create table OPTIONS 
(
	EMPLOYEE_ID NUMBER(6),
	DEPARTMENT_ID NUMBER(4),
	CHOICE NUMBER(2),
	PRIMARY KEY(EMPLOYEE_ID, DEPARTMENT_ID)
);

ALTER TABLE OPTIONS ADD FOREIGN KEY(EMPLOYEE_ID) references EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE OPTIONS ADD FOREIGN KEY(DEPARTMENT_ID) references DEPARTMENTS(DEPARTMENT_ID);


create table LIMITS 
(
DEPARTMENT_ID NUMBER(4),
LIMIT NUMBER(2),
PRIMARY KEY(DEPARTMENT_ID)
);

ALTER TABLE LIMITS ADD FOREIGN KEY(DEPARTMENT_ID) references DEPARTMENTS(DEPARTMENT_ID);


CREATE TABLE EMPLOYEE_DEPARTMENT
(
EMPLOYEE_ID NUMBER(6),
DEPARTMENT_ID NUMBER(4),
PRIMARY KEY(EMPLOYEE_ID, DEPARTMENT_ID)
);

ALTER TABLE EMPLOYEE_DEPARTMENT ADD FOREIGN KEY(EMPLOYEE_ID) references EMPLOYEES(EMPLOYEE_ID);

ALTER TABLE EMPLOYEE_DEPARTMENT ADD FOREIGN KEY(DEPARTMENT_ID) references DEPARTMENTS(DEPARTMENT_ID);


CREATE TABLE DEPARTMENT_SALARY 
(
DEPARTMENT_ID NUMBER(4),
TOTAL_SALARY NUMBER(8,2),
PRIMARY KEY(DEPARTMENT_ID)
);


ALTER TABLE DEPARTMENT_SALARY ADD FOREIGN KEY(DEPARTMENT_ID) references DEPARTMENTS(DEPARTMENT_ID);